### ISSUE TITLE
Could you explain how to use your files? I need just read NTFS fs

### ISSUE THREAD

**Issue by metcenger** [tpunix/H750PI_proj#1]
Which structure should I fill and to where transfer this data? And what function should I call for read USB files?

**Comment by tpunix** [comment]
The file you need: tntfs.h fs_ntfs.c fs_util.c
The function you must provide In tntfs.h:
  printk/printf output function
  malloc/free function

How to use:
  you need a BLKDEV object. Fill with sector read/write function, and call f_initdev, then f_mount. you can see the example in this file: Main/tusb_host_user.c

**Comment by metcenger** [comment]
Thanks. I'll try to make it. I'll write here my results of how it works. Or I'll ask some additional questions.
First qustion-  BLKDEV object- what is it? Where can I take it?

**Comment by metcenger** [comment]
And I can't understand: here we have call for a sector functions, as you mention.
```
static int usb_msc_read_sector(void *itf, u8 *buf, u32 start, int size)
{
	return tusbh_msc_block_read((tusbh_interface_t*)itf, 0, start, size, buf);
}
```
sector has 512 bytes. But inside it we call func for reading block- 4096 bytes usualy.
So what we must read? Sector or block?

**Comment by metcenger** [comment]
Ok, cleared up a little.
Function above wants a sectors and count of it. Not blocks.

Next:
I have layout
![image](https://github.com/tpunix/H750PI_proj/assets/11522773/18f268ea-7dad-45cc-859d-bfea233640ec)

How can I see all directories and files from root of flash?

**Comment by tpunix** [comment]
use f_list: f_list("usb0:/");

**Comment by metcenger** [comment]
Thanks, your library works.
I can see directories and directories inside directories. And files inside directories. Also I able to read file content.

But I have a question regarding some block of code:
function
```
BLKDEV *f_getdev(char *path, int *part, char **rest_path)
{
	char devname[8], *p; 
	BLKDEV *bdev;
	int i;
	...
	...
	...
```
has 8 bytes for a path. Due to it I wasn't able to use some long path name like:
"usb0:/dir22/dir221/testFile.txt"
When I increased it size to 50- everything worked properly.

What reason to use 8 size? What maximum size that can I use for it? I need long paths.

**Comment by tpunix** [comment]
There have a bug ... use this code:
`	p = strchr(path, ':');`
`	if(p==NULL)`
`		return current_dev;`
`	memcpy(devname, path, 8);`
`	devname[p-path] = 0;`
`	p += 1;`

**Comment by metcenger** [comment]
Hi! Your new code works properly. May I use long names file with this the new code? Will it works?

**Comment by metcenger** [comment]
in this function- should we take only device name? usb0- in my case? Therefore 8 length is enought? 
No need more than 8 length?
![image](https://github.com/tpunix/H750PI_proj/assets/11522773/3685834c-0c92-4c75-953a-b7206da7b2f6)

**Comment by tpunix** [comment]
yes. only device name is used. 8 is enought.
